### ISSUE TITLE
Functional Board changes for final revison

### ISSUE THREAD

**Issue by securelyfitz** [Blevene/LabsConBadge_2023#12]
consolidating all board revisions in one issue:

- [x] change IRDA footprint, correcting tx and rx (#8  and #11)
- [x] fix usb d+ and d-
- [x] fix vreg footprint (#2)
- [x] fix SPI flash ground pin disconnected
- [x] fix 'run' pin floating
- [x] fix IREDC resistor to 330 ohms
- [x] confirm crystal footprint
- [x] move usb connector to the left a bit to clear capacitor on oled back
- [x] move irda to the right to clear oled header
- [x] add stemmaQT header (#7)
- [x] add neopixels (#7)
- [x] add power switch (#3)
- [x] add vusb 1117 vreg (#3)
- [x] connect gpio to vusb to address #9
- [x] add neopixel power control fet
- [x] finalize dimensions
- [x] route neopixels
- [x] add lanyard hole(s)
- [x] label on/off switch
- [x] identify pin 1's
- [x] rotate qwiic connector
- [x] rotate power switch
- [x] replace buttons with solder jumpers or pads
- [x] fix irda transciever, again (solder jumper, just in case?)
- [x] add fiducials
- [x] make shout-out gold
- [x] redo front artwork
